/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clienteteatro;

import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iFreuk
 */
public class Cartelera extends javax.swing.JFrame {

    /**
     * Creates new form Cartelera
     */
    public Cartelera() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCartelera = new javax.swing.JTable();
        AnnoIni = new javax.swing.JSpinner();
        AnnoFinal = new javax.swing.JSpinner();
        MesIni = new javax.swing.JSpinner();
        DiaIni = new javax.swing.JSpinner();
        DiaFinal = new javax.swing.JSpinner();
        MesFinal = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Boleteria");
        setName(""); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaCartelera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produccion", "Teatro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaCartelera.setRowHeight(45);
        TablaCartelera.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaCartelera);
        if (TablaCartelera.getColumnModel().getColumnCount() > 0) {
            TablaCartelera.getColumnModel().getColumn(0).setResizable(false);
            TablaCartelera.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 740, 400));

        AnnoIni.setModel(new javax.swing.SpinnerNumberModel(2019, 2019, 2022, 1));
        getContentPane().add(AnnoIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 70, -1));

        AnnoFinal.setModel(new javax.swing.SpinnerNumberModel(2022, 2019, 2022, 1));
        getContentPane().add(AnnoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 70, -1));

        MesIni.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        getContentPane().add(MesIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        DiaIni.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        getContentPane().add(DiaIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        DiaFinal.setModel(new javax.swing.SpinnerNumberModel(31, 1, 31, 1));
        getContentPane().add(DiaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, -1, -1));

        MesFinal.setModel(new javax.swing.SpinnerNumberModel(12, 1, 12, 1));
        getContentPane().add(MesFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Fecha Final:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fecha Inicio:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        BotonConfirmar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonConfirmar.setText("Confirmar");
        BotonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConfirmarActionPerformed
        String tempIni = AnnoIni.getValue().toString()+ "-" + MesIni.getValue().toString()+"-"+ DiaIni.getValue().toString();
        String tempFinal = AnnoFinal.getValue().toString()+ "-" + MesFinal.getValue().toString()+"-"+ DiaFinal.getValue().toString();
        Date Ini = Date.valueOf(tempIni);
        Date Final = Date.valueOf(tempFinal);
        
        DefaultTableModel modelo = (DefaultTableModel) TablaCartelera.getModel();
        try {
            ClienteTeatro.VerCartelera(Ini, Final, modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Cartelera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cartelera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AnnoFinal;
    private javax.swing.JSpinner AnnoIni;
    private javax.swing.JButton BotonConfirmar;
    private javax.swing.JSpinner DiaFinal;
    private javax.swing.JSpinner DiaIni;
    private javax.swing.JSpinner MesFinal;
    private javax.swing.JSpinner MesIni;
    private javax.swing.JTable TablaCartelera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
